//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Currency.Converter.Client.ConverterServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConverterServiceReference.IConverterService")]
    public interface IConverterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConverterService/Converter", ReplyAction="http://tempuri.org/IConverterService/ConverterResponse")]
        string Converter(string value, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConverterService/Converter", ReplyAction="http://tempuri.org/IConverterService/ConverterResponse")]
        System.Threading.Tasks.Task<string> ConverterAsync(string value, string lang);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConverterServiceChannel : Currency.Converter.Client.ConverterServiceReference.IConverterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConverterServiceClient : System.ServiceModel.ClientBase<Currency.Converter.Client.ConverterServiceReference.IConverterService>, Currency.Converter.Client.ConverterServiceReference.IConverterService {
        
        public ConverterServiceClient() {
        }
        
        public ConverterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConverterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConverterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConverterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Converter(string value, string lang) {
            return base.Channel.Converter(value, lang);
        }
        
        public System.Threading.Tasks.Task<string> ConverterAsync(string value, string lang) {
            return base.Channel.ConverterAsync(value, lang);
        }
    }
}
